# Generated by Django 3.1.3 on 2020-11-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_latitude', models.FloatField()),
                ('geo_longitude', models.FloatField()),
                ('address', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('gender', models.CharField(max_length=1)),
                ('company', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('geo_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geolocation')),
            ],
        ),
    ]
