# Generated by Django 3.1.3 on 2020-11-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='geo_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='geo_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
